#!/bin/sh

MESSAGE="Usage: deploy [env] - env is develop, staging, demo, production"

if [ "$#" -ne 1 ]
then
  echo $MESSAGE
  exit 1
fi

  case $1 in
	develop)
		BRANCH=develop
		ENV=develop
		BACKEND_URL=http://develop-api.ejust.law
		;;
	staging)
		BRANCH=staging
		ENV=staging
		BACKEND_URL=http://staging-api.ejust.law
		break
		;;
        demo)
                BRANCH=master
                ENV=demo
		BACKEND_URL=http://demo-api.ejust.law
		break
                ;;
        production)
                BRANCH=master
		ENV=production
		BACKEND_URL=http://api.ejust.law
                break
                ;;
	*)
		echo "This environment do not exist : "$1
		echo $MESSAGE
		exit 1
		;;
  esac

GIT_CO="git clean -f && git co $BRANCH && git pull origin $BRANCH && npm install"
cd src/ejust-web && eval $GIT_CO

for d in /home/mohamed/ejust/*$ENV/*/ ; do
	echo "GENERATE TENANT : $(basename $d)"
	GENERATE="TENANT=$(basename $d) EJUST_BACKEND_URL=$BACKEND_URL DESTINATION_PATH=/home/mohamed/ejust/$ENV webpack --config webpack.exp.config.js --profile --colors"
	eval $GENERATE
done
