#!/bin/sh

API=$2-api
WEB=$2-web
BRANCH_DEVELOP=develop
BRANCH_STAGING=staging
BRANCH_DEMO=master
BRANCH_PRODUCTION=master

if [ "$#" -ne 2 ]
then
  echo "Usage: deploy [env] [project] - env is develop, staging, demo, production - project can be ejust supervision concreet..."
  exit 1
fi

  case $1 in
	develop)
		BRANCH=$BRANCH_DEVELOP
		;;
	staging)
		BRANCH=$BRANCH_STAGING
		break
		;;
        demo)
                BRANCH=$BRANCH_DEMO
                break
                ;;
        production)
                BRANCH=$BRANCH_PRODUCTION
                break
                ;;
	*)
		BRANCH=develop
		;;
  esac

RUN_PM2="cd $HOME/$2/$BRANCH/$API && NODE_ENV=$BRANCH NODE_SUPERVISION_ENV=$BRANCH SHOW_EXPLORER=true pm2 start server/server.js --name $BRANCH-$2"

RESTART_PM2="pm2 restart $BRANCH-$2"

GIT_RESET="git reset --hard origin/$BRANCH && git clean -f"
GIT_CO="git co $BRANCH"
GIT_PULL="git pull origin $BRANCH"
(mkdir -p $HOME/$2/$BRANCH/$API && cd $HOME/src/$API && eval $GIT_CO && eval $GIT_RESET && git clean -f && eval $GIT_PULL && yarn && rm -Rf $HOME/$2/$BRANCH/$API && mkdir -p $HOME/$2/$BRANCH/$API/client && cp -a * $HOME/$2/$BRANCH/$API) && (cd $HOME/src/$WEB && eval $GIT_RESET && rm -Rf build && git pull origin $BRANCH && yarn && yarn run build && cp -a $HOME/src/$WEB/build/* $HOME/$2/$BRANCH/$API/client && eval $RUN_PM2 && eval $RESTART_PM2)
